name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    
    - name: Build Docker image for ARM64
      run: cd docker && docker buildx build --platform linux/arm64 --tag orin:latest .
