name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image for ARM64
      run: docker buildx build \
          --platform linux/arm64 \
          --file docker/Dockerfile \
          --tag orin:latest
